require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-hc
Style/Documentation:
  Enabled: false
AllCops:
  NewCops: enable
RSpec/MultipleExpectations:
  Max: 2
Metrics/AbcSize:
  Max: 19
Layout/LineLength:
  Max: 155
Metrics/MethodLength:
  Max: 18
